In [3]:
import numpy as np


In [4]:
arr1 = np.array([1,2,3,4,5])

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.ndim

1

In [8]:
arr1 = np.array([1,2,3,4,5], dtype =np.float)

C:\Users\User\AppData\Local\Temp/ipykernel_5756/1367463419.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4,5], dtype =np.float)


In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2 = np.arange ( 0, 10 )
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr3 = np.arange (0, 10, 1.5)
arr3

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

Practick 
 create array 1-dim through arange method and check ndim, shape, find the root of std
 # create 2 matrices with size 12 and 12, 
#add values
#through slicing get an optional row, columnd
#get values which are bigger than 5

In [12]:
arr_random = np.random.random((10,))
arr_random


array([0.70286058, 0.85386841, 0.28774447, 0.1968126 , 0.8517745 ,
       0.82033566, 0.32657312, 0.46147534, 0.1107349 , 0.58758923])

In [13]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2_sqrt = np.sqrt(arr2)
arr2_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
arr6 = np.arange(10,20)
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
arr2 + arr6

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [19]:
arr2 * arr6

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [20]:
arr2.sum()

45

In [21]:
arr6.std()

2.8722813232690143

In [22]:
arr6 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
# create array 1-dim through arange method and check ndim, shape, find the root of std

In [42]:
a = np.array([1, 10])
a

array([ 1, 10])

In [43]:
b = np.arange (10, 20) 
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
b.shape

(10,)

In [45]:
b.ndim

1

In [46]:
b_sqrt = np.sqrt(b)
b_sqrt

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [47]:
# after  exercise

In [49]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.insert(arr2, 5, 10)

array([ 0,  1,  2,  3,  4, 10,  5,  6,  7,  8,  9])

In [51]:
np.delete(arr2,5)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [55]:
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
arr4 = np.array([1, 10, 5, 33, 3])
np.sort(arr4)

array([ 1,  3,  5, 10, 33])

In [58]:
arr1

array([1., 2., 3., 4., 5.])

In [59]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr = np.concatenate((arr1, arr2))
arr

array([1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
arr [(arr < 5)]

array([1., 2., 3., 4., 0., 1., 2., 3., 4.])

In [68]:
arr2[(arr2<10) & (arr2>5)]

array([6, 7, 8, 9])

In [69]:
arr2[(arr2<6) | (arr2>7)]

array([0, 1, 2, 3, 4, 5, 8, 9])

In [71]:
arr[(arr < 3) | (arr > 17)]

array([1., 2., 0., 1., 2.])

In [72]:
arr[(arr < 3) & (arr > 17)]

array([], dtype=float64)

In [92]:
matrix1 = np.array([(1,2,30),(4,5,6),(7,8,9)])
matrix1

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [93]:
matrix2 = np.array([(21,52,66),(85,65,95),(45,65,85)])
matrix2

array([[21, 52, 66],
       [85, 65, 95],
       [45, 65, 85]])

In [94]:
matrix2.shape

(3, 3)

In [95]:
matrix2.ndim

2

In [96]:
matrix2.size

9

In [98]:
matrix2.reshape(1,9)

array([[21, 52, 66, 85, 65, 95, 45, 65, 85]])

In [99]:
matrix2

array([[21, 52, 66],
       [85, 65, 95],
       [45, 65, 85]])

In [100]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [106]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
np.empty(2)

array([1.43098058e-311, 0.00000000e+000])

In [110]:
matrix2

array([[21, 52, 66],
       [85, 65, 95],
       [45, 65, 85]])

In [112]:
matrix3 = np.array([(10,11,85),(52,85,66),(78,55,68)])
matrix3

array([[10, 11, 85],
       [52, 85, 66],
       [78, 55, 68]])

In [113]:
matrix2 + matrix3

array([[ 31,  63, 151],
       [137, 150, 161],
       [123, 120, 153]])

In [114]:
np.dot (matrix3,matrix2)

array([[ 4970,  6760,  8930],
       [11287, 12519, 17117],
       [ 9373, 12051, 16153]])

In [115]:
matrix1

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [116]:
np.delete(matrix, 2, axis=0) #axis = 0 - row, axis = 1 - column

array([[21, 52, 66],
       [85, 65, 95]])

In [118]:
np.delete(matrix, 2, axis=1)

array([[21, 52],
       [85, 65],
       [45, 65]])

In [119]:
np.mean(matrix1, axis=0)

array([ 4.,  5., 15.])

In [121]:
#[][][] - rows 0
##[][][]
#cols - 1

In [122]:
matrix2

array([[21, 52, 66],
       [85, 65, 95],
       [45, 65, 85]])

In [123]:
matrix

array([[21, 52, 66],
       [85, 65, 95],
       [45, 65, 85]])

In [125]:
matrix[1,2] #0,1

95

In [128]:
matrix[:,1] # [rows, columns]

array([52, 65, 65])

In [131]:
matrix < 5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [137]:
matrix[matrix1 < 5] #table[table > 100]

array([21, 52, 85])

In [138]:
# create 2 matrices with size 12 and 12, 
#add values
#through slicing get an optional row, column
#get values which are bigger than 5

In [140]:
# ex

In [173]:
matrix_ex = np.array([(21,36,33), (21,52,85),(12,35,85),(23,32,32)])
matrix_ex

array([[21, 36, 33],
       [21, 52, 85],
       [12, 35, 85],
       [23, 32, 32]])

In [174]:
matrix_ex2 = np.array([(18,25,65),(54,56,65),(65,54,54),(85,65,45)])
matrix_ex
matrix_ex2

array([[18, 25, 65],
       [54, 56, 65],
       [65, 54, 54],
       [85, 65, 45]])

In [175]:
matrix_ex + matrix_ex2

array([[ 39,  61,  98],
       [ 75, 108, 150],
       [ 77,  89, 139],
       [108,  97,  77]])

In [177]:
matrix_ex [1,2]

85

In [178]:
matrix_ex [2,2]

85

In [179]:
matrix_ex [3, 1]

32

In [181]:
matrix_ex [matrix_ex > 32]

array([36, 33, 52, 85, 35, 85])

In [182]:
matrix_ex [matrix_ex < 52]

array([21, 36, 33, 21, 12, 35, 23, 32, 32])

In [183]:
matrix_ex [matrix_ex > 5]

array([21, 36, 33, 21, 52, 85, 12, 35, 85, 23, 32, 32])